### ISSUE TITLE
The mail icon next to the subscribe link doesn't display properly on Firefox

### ISSUE THREAD

**Issue by weijia-cheng** [standardebooks/web#101]
![Screenshot from 2021-01-08 12-24-54](https://user-images.githubusercontent.com/1240463/104060948-8b67ea00-51ac-11eb-923c-cb639347be1f.png)

This is how it displays on Firefox for me.

In contrast, it works fine on Chrome for whatever reason:

![Screenshot from 2021-01-08 12-25-36](https://user-images.githubusercontent.com/1240463/104061018-a6d2f500-51ac-11eb-8467-0a748bffc9a0.png)

**Comment by acabal** [comment]
Did you clear your cache? You can try opening the inspector's network tab to ensure it does a fresh reload without the cache.

**Comment by weijia-cheng** [comment]
Ah, looks like clearing the cache fixed the issue!
