### ISSUE TITLE
Collections view

### ISSUE THREAD

**Issue by robinwhittleton** [standardebooks/web#102]
https://standardebooks.org/collections should show all of the collections on the site.

(from this comment https://news.ycombinator.com/item?id=25788256)

**Comment by acabal** [comment]
Good idea. If you'd like to work on it, go for it!

**Comment by robinwhittleton** [comment]
I never really got the web site up and running properly locally, and it seems to have changed a good deal since the last time I looked into it. I can’t see how this is going to have a chance of running on macOS without some real PHP skill (which I don’t have) and I don’t have the time at the moment to put into learning how to do it / setting it up in a VM. So I’m going to have to pass this over to someone else I’m afraid, unless things change.

**Comment by jwfxpr** [comment]
As an interim measure, until a proper solution is developed that pulls the collection data from the corpus, if a manual list is added to the website there are currently three "best of" collections.

Modern Library's 100 Best Novels: https://standardebooks.org/collections/modern-librarys-100-best-novels

Pulitzer Prize Winners: https://standardebooks.org/collections/pulitzer-prize-winners

The Guardian's best 100 novels in English: https://standardebooks.org/collections/the-guardians-best-100-novels-in-english-2015

**Comment by jwfxpr** [comment]
BBC's 100 greatest British novels: https://standardebooks.org/collections/the-bbcs-100-greatest-british-novels-2015

**Comment by jwfxpr** [comment]
Telegraph's Greatest Villains in Literature: https://standardebooks.org/collections/the-telegraphs-greatest-villains-in-literature

**Comment by acabal** [comment]
Closed due to inactivty
