### ISSUE TITLE
Science fiction tag shows no results

### ISSUE THREAD

**Issue by mgbennet** [standardebooks/web#114]
Currently, [https://standardebooks.org/tags/science-fiction](https://standardebooks.org/tags/science-fiction) yields no results. This is the url that the tags link on book pages uses. Other tags work fine. I suspect this is because science fiction is the only two word tag.
Also, [https://standardebooks.org/tags/science+fiction](https://standardebooks.org/tags/science+fiction) (changing the - to a + in the tag name) seems to work.

**Comment by acabal** [comment]
This should be fixed now!
