### ISSUE TITLE
Typography manual uses hair space instead of thin space

### ISSUE THREAD

**Issue by link2xt** [standardebooks/web#12]
See https://standardebooks.org/contribute/typography#quotation-marks

According to TeX book (and https://en.wikipedia.org/wiki/Thin_space, which refers to it), it should be thin space, `&thinsp;` See also https://theeditorsblog.net/2017/04/14/quotes-within-quotes/

**Comment by acabal** [comment]
Our manual differs from the TeX manual on this point :)
