### ISSUE TITLE
Dead Readium link in "How to Use Our Ebooks"

### ISSUE THREAD

**Issue by geophree** [standardebooks/web#138]
The [`https://readium.org/about/applications.html/`](https://readium.org/about/applications.html/) link in the following line currently 404s:
https://github.com/standardebooks/web/blob/670f5245602d24136741d72514b884dae894848f/www/help/how-to-use-our-ebooks.php#L21
I poked around on [`readium.org`](https://readium.org), but didn't find an equivalent page.  The closest was [`https://readium.org/awesome-readium/`](https://readium.org/awesome-readium/).

**Comment by acabal** [comment]
Thanks, this should be fixed now!
