### ISSUE TITLE
Allow sorting ebooks by reading ease and word count

### ISSUE THREAD

**Issue by tuskpot** [standardebooks/web#15]
In a [post on the mailing list](https://groups.google.com/forum/#!topic/standardebooks/N9QGltCu4as), a visitor suggested allowing the user to sort the [Browse Ebooks](https://standardebooks.org/ebooks/) page by reading ease. In addition, I also suggest allowing the user to sort by word count.

I took a look at the EBook class to see if there were any other properties that would be good for sorting, but I didn't really see any others. I considered suggesting reading time, but it looks like this is simply word count divided by 275 words per minute for all books, so sorting by reading time would be identical to sorting by word count. (Although, users may not realize that. I always assumed that reading time was calculated on both word count and reading ease!)

To keep things simple, I think it's sufficient to have a single sort direction for these new criteria:
* Reading ease: easiest first
* Word count: fewest words first

**Comment by tuskpot** [comment]
Here's a [rough example on codepen](https://codepen.io/anon/pen/axZXKB) of how a large number of sort criteria could be hidden behind a disclosure widget. This uses the \<details\> HTML element, so it doesn't require any javascript.

Support for \<details\> [appears to be quite good](https://caniuse.com/#search=details), by relative usage. Browsers that don't support it should simply show the inner elements by default, so the functionality would still be available.

**Comment by mgbennet** [comment]
Implemented with #24
