### ISSUE TITLE
producing an ebook step by step page - commit messages

### ISSUE THREAD

**Issue by pcrooker** [standardebooks/web#153]
To better encourage correct use of commit messages, I've rewritten the first commit wording at the end of section 5, clarifying the role of the commit messages and that they should be used exactly as shown on the page. Also, rewrote the [Editorial] commit instructions at the end of section 13, to make it clearer what is required for this type of commit, enclosed in an alert for emphasis. 

I've created a branch on my system with the changes. It looks like I don't have access to create a pull request (I've never done one before). Shall I just post the altered `producing-an-ebook-step-by-step.php` file here or ???

**Comment by acabal** [comment]
You should be able to create a PR for the web repo. It's just like any other Github repo. What does it say when you try it?

**Comment by pcrooker** [comment]
I was using the website "create a pull request". It goes to a Compare Changes page, the "create pull request is greyed out (well, greened out, anyway you can't click on it) and says to "Choose different branches or forks above to compare", I select master and it says there isn't anything to compare.

When I try to just push from my branch I get an auth error - "Support for password authentication was removed on August 13, 2021. Please use a personal access token instead." I did set up using an ssh key for my Tarzan repo but I suppose my key isn't registered with your repo.

**Comment by acabal** [comment]
You first have to fork the web repo to your own Github account, then make the changes there. Once you do that you should be able to create a PR to merge your branch with its changes into our master repo. There should be plenty of tutorials online on how to do this since the Github flow is sort of proprietary.

**Comment by pcrooker** [comment]
bloody hell.... I wondered why they were mentioning forking so casually. Thanks for explaining it, I never would have guessed. I'll have a go.
