### ISSUE TITLE
Front page should not advertise illustrations

### ISSUE THREAD

**Issue by bentley** [standardebooks/web#154]
[devices.png](https://github.com/standardebooks/web/blob/master/www/images/devices.png) and [devices@2x.png](https://github.com/standardebooks/web/blob/master/www/images/devices%402x.png) depict illustrations within our edition of *Treasure Island*. I think this causes some confusion for people less familiar with the current SE policy on illustrations, and gives them certain expectations that result in wordy discussions on the mailing list.

Speaking for myself, it did give me the wrong impression of the illustrations policy when I first got involved.

**Comment by acabal** [comment]
Yes, I suppose we should change that. I don't have time to at the moment, so if anyone is interested please jump in.
