### ISSUE TITLE
Add link to author page on ebook page.

### ISSUE THREAD

**Issue by PyroLagus** [standardebooks/web#16]
It would be nice to have a link to the author page (for instance https://standardebooks.org/ebooks/maurice-leblanc/) on the pages for the specific books (https://standardebooks.org/ebooks/maurice-leblanc/the-eight-strokes-of-the-clock/alexander-teixeira-de-mattos for example). The authors name is already listed under the title, so it may be a good idea to just make that a hyperlink. That would also mirror the way it works in the search results, so it should be intuitive.

**Comment by acabal** [comment]
Sure, sounds like a good idea. Pull requests welcomed.

**Comment by PyroLagus** [comment]
Underline?
![underline](https://user-images.githubusercontent.com/4579165/57814750-b3d2e300-7742-11e9-92d3-fc3b00351f6c.png)

Or no underline?

![no-underline](https://user-images.githubusercontent.com/4579165/57814749-b2091f80-7742-11e9-889f-c9e982cc45ee.png)

**Comment by acabal** [comment]
No underline. Thanks!
