### ISSUE TITLE
Documentation on downloading in paperwhite/voyage/oasis browser

### ISSUE THREAD

**Issue by IdiosApps** [standardebooks/web#178]
I didn't want to find a USB cable for my kindle, and figured I'd try **downloading books in my Oasis/Paperwhite browser** seen as "send to kindle" doesn't play nice with azw3 (thanks Amazon).

The download dialogue took a few seconds to appear, but the book downloaded directly to the device - and it shows at the top of my library 🥳 

My suggestion is that:
-  we note this as method 2 under "Amazaon Kindle eInk Devices" in the [FAQ](https://standardebooks.org/help/how-to-use-our-ebooks#kindle-faq). 
- we figure out if there's a way to guarantee the kindle will download the _Kindle cover thumbnail_ instead of opening it in a new page. 
    - I did a quick look and I guess it's Kindle not understanding mime-types/content disposition in the same way as a desktop browser. I found the [optional text in php](https://github.com/standardebooks/web/blob/master/www/ebooks/ebook.php#L241), but can't see what to check next.

The browsing experience is OK, and #126 addresses improving it.

**Comment by acabal** [comment]
Sure, we can add that to the Kindle how-to. Can you create a pull request?

I don't think it's going to be possible to get Kindle to correctly download the thumbnail, because it has to be placed into a special system folder for it to work. So, your Kindle would probably download it to some downloads folder, and where do you go from there? It'd be too complicated.

**Comment by IdiosApps** [comment]
I will open a PR about it.

Okay, that makes sense about the thumbnail. Do you know if "send to kindle" would place it in an acceptable folder to be used as a thumbnail?
```
Send to Kindle supports the following document formats:
...
JPEG (.jpg), GIF (.gif), Bitmap (.bmp), and PNG (.png) images.
```

**Comment by acabal** [comment]
I highly doubt it, but you could try!
