### ISSUE TITLE
Suggested alternative to GitHub

### ISSUE THREAD

**Issue by celtic-coder** [standardebooks/web#182]
Hi Alex (@acabal),

In the **Help Wanted** section of the README, you mention the need for a self-hosting alternative to GitHub. The _privacyguides.org_ organisation are currently discussing this question in two separate discussions:

- [Privacy oriented GitHub alternatives?](https://github.com/privacyguides/privacyguides.org/discussions/1374)
- [Is there any privacy friendly alternative to github.](https://github.com/privacyguides/privacyguides.org/discussions/1557)

Several alternatives are suggested, but one that you might want to consider is **Codeberg**. In the thread it is [mentioned](https://github.com/privacyguides/privacyguides.org/discussions/1557#discussioncomment-3166110) as: 
> an EU non-profit organization which runs on Gitea

[Gitea](https://gitea.io/en-us/) describe themselves as:
> A painless, self-hosted Git service

Interestingly, [Matthew Butterick](https://github.com/mbutterick) of [Practical Typography](https://practicaltypography.com/), recently moved his GitHub repos to Codeberg. There was a recent heavily commented discusson at: [opinions sought: costs & benefits of switching to self-hosted Git server?](https://github.com/mbutterick/pollen-users/issues/131)

Perhaps there might be some ideas in these links that would help with the decision on where best to move?

Kind Regards,
Liam

**Comment by acabal** [comment]
Thanks Liam! If we do switch from Github, we want a self-hosted solution. Our concern with Github isn't privacy, rather it's  being charge of our own data and not relying on others for infrastructure. 

So the question is, what product can be self hosted and how do we do it with the minimum amount of maintenance pain? This probably means something like Docker but I don't have any Docker experience. Gitea seems to be the closest to Github in terms of functionality and is probably the frontrunner in terms of options.

**Comment by celtic-coder** [comment]
Hi Alex (@acabal),

Unfortunately, I don't have any experience in self-hosting, but I had recently come across these threads and felt that they might be useful in providing some background.

Matthew Butterick has recently moved his [Pollen project](https://git.matthewbutterick.com/mbutterick/pollen/commits/branch/master), among many others, to his own server using Codeberg and the functionality looks comparable to GitHub. It is certainly worth considering.

Kind Regards,
Liam
