### ISSUE TITLE
CSS Bug when hovering 3D Book

### ISSUE THREAD

**Issue by Modjular** [standardebooks/web#186]
There seems to be a bug with the CSS for the 3D 'Book' in the **download** section
<img width="218" alt="Screen Shot 2022-07-27 at 10 21 34 AM" src="https://user-images.githubusercontent.com/8238329/181312090-b038d1d6-d569-469b-9543-dfca837378d0.png">
<img width="218" alt="Screen Shot 2022-07-27 at 10 21 50 AM" src="https://user-images.githubusercontent.com/8238329/181312142-ff8744da-9617-4697-95dc-27584a4bec37.png">

**Comment by acabal** [comment]
What browser and version are you using?

**Comment by Modjular** [comment]
Chrome `103.0.5060.53 (Official Build) (arm64) `

**Comment by acabal** [comment]
I can't duplicate this on Chromium `103.0.5060.134 (Official Build) (64-bit)`. Maybe there's a browser extension you have installed that is messing with the layout. If you can investigate further on your own that would be helpful, otherwise I'll close this for now.

**Comment by Modjular** [comment]
For sure. I'll take a look myself.
Could you point me in the direction of the CSS responsible for the animation? I wandered around `www/ebooks/ebook.php` for a bit but couldn't find it.

**Comment by acabal** [comment]
All web CSS is in one file, https://github.com/standardebooks/web/blob/master/www/css/core.css

You can use your browser's web inspector to look at the element and see what CSS is being applied and where it comes from. There is no JS on the site and the CSS is not compiled so it should be very straightforward to use the inspector to look at exactly what's going on in your case.

**Comment by acabal** [comment]
The HTML for the figure is here: https://github.com/standardebooks/web/blob/75ed29db63691b2635c3dc0ea05796c69d2d67fe/www/ebooks/ebook.php#L215-L221

But you should not change the HTML. A fix should only change the CSS to something that works in your case.

**Comment by Modjular** [comment]
@acabal 
My bad, it's not a bug. More of a side-effect of enabling **Reduce motion** in Macos 12
<img width="780" alt="image" src="https://user-images.githubusercontent.com/8238329/181596252-4f9f06ff-abfb-4c66-b125-b72fe0789115.png">

I didn't know this media query existed: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion
The query sets all `transitions` to `none`, but it doesn't seem to affect `figure::after` or `figure::before`

**Comment by acabal** [comment]
It looks like we attempt to honor that here: https://github.com/standardebooks/web/blob/75ed29db63691b2635c3dc0ea05796c69d2d67fe/www/css/core.css#L3577-L3591

Is it a bug in our CSS, or a bug in Safari, that's causing this issue?

**Comment by acabal** [comment]
This was a bug in our CSS, which I've fixed. Force a page refresh using ctrl + f5 and the book should be rendered correctly, without animation.
