### ISSUE TITLE
List of Authors

### ISSUE THREAD

**Issue by donatj** [standardebooks/web#189]
https://standardebooks.org/feeds/atom/authors

So this page has the full list which I only found after poking around the codebase for a minute.

It'd be super helpful to have like an "Authors" link in the header or footer - or like a dropdown of authors on the Books page?

I'd even happily donate the time to build it if I got a little direction ;)

**Comment by acabal** [comment]
There's a link in the site footer to https://standardebooks.org/feeds which lists all the available feeds. You can drill down from there to see the different feed options for your preferred feed format. Does that clear things up?

**Comment by donatj** [comment]
No. I'm not looking for feeds.

I'm looking for a way to find books by _specific authors_ from the website. Right now if you're looking for books by an author, you have to paginate through _all the books_ until you find one by them and then click on their name - which takes you to https://standardebooks.org/ebooks/apuleius

I want a way, from the website to find an author without paginating through books.

**Comment by acabal** [comment]
In that case we'd need some help doing that. Putting an index in `/authors` would probably be the way to go about that. `/authors/<AUTHOR_SLUG>` could be an Apache internal redirect to `/ebooks/<AUTHOR_SLUG>`, preserving the URL but resusing the author listing code.

**Comment by acabal** [comment]
If you'd like to work on this, then please go ahead. Let me know if you have any specific questions as you get started!

**Comment by donatj** [comment]
Yup, I will poke at it ;)
