### ISSUE TITLE
allow sorting by first publication date

### ISSUE THREAD

**Issue by stragu** [standardebooks/web#196]
In navigating the list of books, I often want to sort by original publication date to have an idea of how contemporary the writing is. In particular when the reader is not a native English speaker, finding a book that is more likely to read like today's English would be a great help.

**Comment by acabal** [comment]
This is often requested but we don't store publication date because it is unclear in many cases and would also not apply to omnibuses. Sorry! :(

**Comment by stragu** [comment]
Ah that's a shame, but thanks for the quick reply and the great work with Standard eBooks!
