### ISSUE TITLE
Have web view of ebook respect color scheme

### ISSUE THREAD

**Issue by SethRAH** [standardebooks/web#199]
When viewing the text of an ebook online (via either the "Read online" > "Start from the table of contents" or the "Read online" > "Read on one page" links), the page does not respect the color scheme chosen via settings.

More specifically, the functionality I'm desiring is a dark mode so that I can easily read on my phone or on my computer in low light and have a more gentle reading experience. I thought changing the color settings to "Dark" would give me what I want but these pages don't seem to respect that.

In case there is any ebook specific issue here, I was trying to read Spoon River Anthology by Edgar Lee Masters

**Comment by acabal** [comment]
The web view does support dark mode; I use dark mode myself exclusively and it works fine. Perhaps there's a setting in your browser that's incorrect?

You can view the page's source code to confirm that there is a CSS media query for dark mode.

**Comment by SethRAH** [comment]
I confirmed if I switch to a different browser it's respecting those settings. Original browser that wasn't working was duckduckgo on Android. Browser that was working was chrome on Android. I might try and troubleshoot what is going on with duckduckgo later and update this thread but for now I'll switch to a different browser.

Thanks for the quick response.

**Comment by SethRAH** [comment]
I dug around a little bit and I believe, as I've written the title to this issue, it still stands as an issue. Most of the site seems to drive off of the "Color scheme" setting that can be set at https://standardebooks.org/settings. The three options are: Automatic, Light, Dark. Automatic will defer to the OS's color settings, but if the user chooses either Light or Dark, the page overrides the OS's color settings and instead uses the site's setting.

The following use cases reflect this:

1. Have your OS set to dark mode. Navigate to https://standardebooks.org/settings and set the color scheme to "Light". Navigate to the "Read online" > "Start from the table of contents" or the "Read online" > "Read on one page" pages and verify that it incorrectly shows in dark mode.
2. Have your OS set to light mode. Navigate to https://standardebooks.org/settings and set the color scheme to "Dark". Navigate to the "Read online" > "Start from the table of contents" or the "Read online" > "Read on one page" pages and verify that it incorrectly shows in light mode.

Granted, I realize that most of the time the user probably wants to reflect the OS's settings (unless they have a browser that doesn't support the media query like I did or they find that this specific site looks better in the other mode) and therefore this is probably a lower priority but as the feature is presented, it does appear to be a bug.

**Comment by acabal** [comment]
Right, the web site and the "view in your browser" ebooks are two different things. The website is driven by PHP and can read cookies and adjust settings. However when you read a book in your browser, it's just a flat XHTML file. So, we're not going to be able to do any kind of logic like reading cookies in those files, and they rely on prebaked CSS only. Unfortunately there's no way around that right now nor do I think we'll be adding PHP preprocessing to XHTML files.

**Comment by SethRAH** [comment]
That makes a lot more sense (and I was wondering if something like that was happening). I will say though that it looks like the local storage to indicate dark mode is accessible in the xhtml pages and you could maybe use js to read that and modify the styling based on that. I'm happy with the current state to solve my problem though and just included that note as a possible path forward in the future if you decide to implement.
