### ISSUE TITLE
OPDS ordering and categorizing

### ISSUE THREAD

**Issue by anarcat** [standardebooks/web#2]
OPDS entries are ordered. For example, in the main link from the first OPDS feed ([All standard ebooks](https://standardebooks.org/opds/all)), we see the following first few books:

```
The Moon Pool
30 octobre 2017 18 h 17
A group of adventurers search for their friends, who were lost while exploring the otherworldly secrets of a monument discovered on a chain of island ruins.

The Mysterious Affair at Styles
13 novembre 2017 19 h 34
Hercule Poirot solves the mystery of a murder in an English country manor.

The Secret Adversary
29 octobre 2017 23 h 13
Tommy and Tuppence try to solve a mystery, only to find themselves embroiled in schemes of murder, millionares, and diplomats.
```

That's all fine and dandy, but notice how the dates are completely out of order?

It would make much more sense to order those by date. This way this entry could reflect the sort order in the main webpage: by date.

Or we could sort the entries in alphabetical order. This could be a separate feed too.

Another feed could categorize entries by author: the first level would list authors and then books would be listed after.

For example, the [Gutenberg OPDS feed](http://m.gutenberg.org/ebooks/?format=opds) offers to sort by popularity, "latest" or "random". The [Manybooks OPDS](http://manybooks.net/opds/) feed is even better organized; you can see "New titles", "Authors", "Titles" and "Genres" categorizations.

**Comment by acabal** [comment]
Closed due to inactivity
