### ISSUE TITLE
"mail to kindle" not supported for azw3. Switch to epub?

### ISSUE THREAD

**Issue by michaelkirk** [standardebooks/web#205]
I tried and failed to email a book (.azw3) to my kindle following the directions on the site.

Here are the notes on file formats from the site (e.g. from https://standardebooks.org/ebooks/jack-black/you-cant-win)

> **Compatible epub** — All devices and apps except Kindles and Kobos.
>
> **azw3** — Kindle devices and apps. Also download the Kindle cover thumbnail to see the cover in your Kindle’s library. You may be interested in our Kindle FAQ.

Reading that, .azw3 seemed like the right choice, so I downloaded it and emailed it to my kindle. A short while later I received an email from kindle support saying that the azw3 format was not supported.

Full text of their email:

> Dear Kindle Customer,
>
> The following document, sent by you at 04:45 PM on Sat, Nov 26, 2022 GMT , could not be delivered to the address you specified:
>
> * jack-black_you-cant-win.azw3
>
> Send to Kindle supports the following document formats:
> Adobe PDF (.pdf)
> Microsoft Word (.doc, .docx)
> Rich Text Format (.rtf)
> HTML (.htm, .html)
> Text (.txt) documents
> Archived documents (zip , x-zip) and compressed archived documents
> MOBI (.azw, .mobi) (will not support the most up-to-date Kindle features for documents)
> JPEG (.jpg), GIF (.gif), Bitmap (.bmp), and PNG (.png) images .
> 
> Additionally, Send to Kindle emails now supports EPUB (.epub). Later this year, we’ll also be adding EPUB support to the free Kindle app for iOS and Android devices and the Send to Kindle desktop app for PC and Mac.
> 
> If the format of the document that failed is supported (listed above), please ensure the document is not password protected or encrypted, and try sending it again.
> 
> You can learn more about sending personal documents to your Kindle in our product info pages: [https://www.amazon.com/sendtokindle](https://www.amazon.com/gp/f.html?C=1K3L02HPB0IT3&K=388F52WFM0FBV&M=urn:rtn:msg:20221126164547920731d66954486d99f1a46c1bb0p0na&R=1XAZDN7E4I6MB&T=C&U=https%3A%2F%2Fwww.amazon.com%2Fsendtokindle%3Fref_%3Dpe_1825130_597224190&H=KMBDV16B8FEILQWARBNIQT7CPBEA&ref_=pe_1825130_597224190)
> 
> If you would like immediate assistance, please contact customer support at +1-866-321-8851 (US customers) or +1-206-266-0927 (International customers).
> 
> Sincerely,
> Amazon Kindle Support

**Comment by acabal** [comment]
Yes, this is noted in our 'how to' page: https://standardebooks.org/help/how-to-use-our-ebooks#kindle

You must complain to Kindle. Not sure why their own systems don't support the ebook format they invented.
