### ISSUE TITLE
Book titles wrap on narrow displays

### ISSUE THREAD

**Issue by bentley** [standardebooks/web#229]
Here’s a screenshot of the *Persuasion* page in Chromium on the Pixel 7:

![screen](https://user-images.githubusercontent.com/126009/229406157-20e88a71-2272-4763-8acf-47af6243b923.png)

Hard to say how specifically this could be prevented, but hyphenation could help.

**Comment by acabal** [comment]
No way around it. They have to wrap otherwise the will expand the viewport and cause a horizontal scrollbar. Hyphenation is not a great solution either because it often hyphenates at unexpected places or not at all. Container queries may be the answer but not yet ready for prime time in browsers.

**Comment by bentley** [comment]
Bummer!
