### ISSUE TITLE
Step by Step historical anomalies

### ISSUE THREAD

**Issue by vr8hub** [standardebooks/web#230]
In (current) step 12 of the Step by Step guide, "Convert British Quotation to American," the second paragraph says "…must already be typogrified (the previous step in this guide)…". I'm sure that was true at one time, but now it is _four_ steps previous. :) The intervening steps are find-unusual-characters (9), convert footnotes to endnoes (10), and the LOI (11).

Do we want to reword that sentence, or move 12 up to immediately follow typogrify?

Also, the second bullet of step 2 talks in detail about differences between the HTML and epub versions of the PG transcription, which mattered long ago in a distant world where create-draft wasn't as good as it is now. :) Since create-draft is now downloading the transcription directly (for PG, anyway, but that's what the paragraph is about, specifically PG transcriptions), do we still need that bullet?

Which, related, 4.2 still talks about doing it by hand—do we really want people doing that (again, on PG specifically)?

If any changes are desired, I can work on a PR.

**Comment by acabal** [comment]
Thanks, that step reference is fixed now. As for the rest, we can leave it because the guide can also be useful for people following our procedures but not submitting to us.
