### ISSUE TITLE
Wording in 8.7.5.3.2 (Quotation marks)

### ISSUE THREAD

**Issue by vr8hub** [standardebooks/web#231]
>This is a matter of typography and not actual spelling, and is to the expected modern spelling of the last name.

The clause after the comma doesn't sound right to me, but I'm not sure what it's trying to say. Is it "…and is to be _changed_ to the expected modern spelling of the last name."? (Italics only to make the difference obvious here, not to be part of the text.)

**Comment by acabal** [comment]
I think this was already fixed in master
