### ISSUE TITLE
An easy way to download full collection

### ISSUE THREAD

**Issue by kupiqu** [standardebooks/web#25]

**Comment by acabal** [comment]
An OPDS feed is available which you can use in an ereader to download the collection: https://standardebooks.org/opds/

Right now I would rather not script a download of the entire corpus because bandwidth is still limited.

**Comment by kupiqu** [comment]
> An OPDS feed is available which you can use in an ereader to download the collection: https://standardebooks.org/opds/

I never used an opds feed in my kindle before, could you please tell me how I can do that?

**Comment by acabal** [comment]
I'm not sure, but that would be a good question for the mailing list, or a Google search to see if it's possible.

**Comment by kupiqu** [comment]
Thought you knew this was possible in the eink reader by how you said it
above...

Anyway, I will create an script do to it automatically in my system out of
the file.
