### ISSUE TITLE
How many books have been released so far?

### ISSUE THREAD

**Issue by 07416** [standardebooks/web#259]
~~I attempted counting programmatically (all files which end in `_advanced.epub`) and got 613 as a result, applicable to about mid-July (2023).~~

**EDIT**: In fact the count (613) equally applies to other formats. I've modified the title, changing the topic.

[Wikipedia at the time](https://en.wikipedia.org/w/index.php?title=Standard_Ebooks&oldid=1159798858) reports '836 documents'.

The number of ebook pages can be counted by scraping [the standardebooks.org website](https://standardebooks.org/ebooks) (or [repositories](https://github.com/orgs/standardebooks/repositories?type=all) on Github?), but it would be convenient to have the book count tracked officially.

**Comment by acabal** [comment]
Every ebook is available in every format. There are 856 ebooks available right now. At the moment the corpus is being rebuilt to conform to a new standard so some counts may be off for the next day.
