### ISSUE TITLE
OPDS: `dc:issued` should use `http://purl.org/dc/terms/` namespace

### ISSUE THREAD

**Issue by johnfactotum** [standardebooks/web#299]
The `http://purl.org/dc/elements/1.1/` namespace doesn't have the `issued` property.

Probably easier to just use the `/terms/` namespace for everything, which is what the OPDS spec does.

**Comment by acabal** [comment]
Good catch, this should be fixed now. The feeds should rebuild over the next day so it will take some time for the changes to go live.
