### ISSUE TITLE
inject-chapter-navigation-footer depends on se Python module

### ISSUE THREAD

**Issue by sweetgiorni** [standardebooks/web#308]
`scripts/inject-chapter-navigation-footer`, a Python script, imports the `se` package from [standardebooks/tools](https://github.com/standardebooks/tools). The installation instructions in that repo suggest installing with `pipx`, which means that the package is not available for import outside of the virtual environment managed by `pipx`. This results in an import error when running `scripts/deploy-ebook-to-www`, even after the SE toolset has been installed.

Some possible solutions:
- Modify the SE toolset instructions to suggest installation without pipx, perhaps through a user-created virtual environment.
- Modify the instructions in _this_ repo to suggest running `pip install standardebooks` directly.
- Add a `pyproject.toml` to this repo and rely on that tool ecosystem for dependency management.
- Stop importing `se`. Maybe the relevant functionality could be moved to the CLI or outsourced to another tool?

**Comment by acabal** [comment]
Thanks, this has been fixed and the changes should be pushed to this repo in the next few days.
