### ISSUE TITLE
schema.org book markup

### ISSUE THREAD

**Issue by robinwhittleton** [standardebooks/web#33]
We could potentially add metadata markup to our search results and book pages up using the schema.org Book metadata: https://schema.org/Book . This would allow search engines and other automated systems to accurately identify and consume our data. Thoughts?

**Comment by acabal** [comment]
We already do, view source an ebook page and schema.org info is in an ld/json snippet at the top. Is that what you mean?

**Comment by robinwhittleton** [comment]
Oh, oops, I’ve only used metadata attached to the HTML before, not delivered as a JSON object, so I completely missed it at the top of the page 🤦‍♂️
