### ISSUE TITLE
Caesura CSS should probably be tweaked

### ISSUE THREAD

**Issue by robinwhittleton** [standardebooks/web#337]
https://github.com/standardebooks/web/blob/2b47b65437e6acdd0e61b762faa8e93cab35c76c/www/contribute/how-tos/how-to-structure-and-style-large-poetic-productions.php#L151-L155

This works fine for a single caesura in a line, but multiple are possible (and present in the Mina Loy I’m working on). I’ve amended my copy to the following, which should work without problem for more than one:
```css
span > span + span{
  margin-left: 1.5em;
}
```
Should we change this here too?

**Comment by EmmaSweeney** [comment]
I'll make the change to the guide when I have some free time this week.

**Comment by acabal** [comment]
If this is a generic update that will work in old books, we should update their CSS to match the new standard as well.

**Comment by EmmaSweeney** [comment]
Ok, I made a PR for this issue (#338) and updated the CSS in The Nibelungenlied.
