### ISSUE TITLE
Broken link in www/help/how-to-use-our-ebooks.php

### ISSUE THREAD

**Issue by kenneth-leblanc** [standardebooks/web#339]
In www/help/how-to-use-our-ebooks.php the link for how to show hidden files and folders on windows leads to a 404 error. The link is an out of date link that applies to windows vista.
The broken link is on line 44.

Below is a new link valid for windows 11.
https://www.howtogeek.com/743079/how-to-show-hidden-files-on-windows-11/

-Ken

**Comment by acabal** [comment]
Thanks, this is now fixed!
