### ISSUE TITLE
Written languages

### ISSUE THREAD

**Issue by KasMA1990** [standardebooks/web#34]
I stumbled upon the web page, and started looking for information on which languages are supported. That is, must all books on there be in english, and if so, what are the sources for the books that were not originally written in english but are still present?

Having information on this on the site would be nice 🙂 

(And thanks for the great work done here!)

**Comment by acabal** [comment]
Hi there, all books must be in English. Translations to English are OK. See this list of books we do and don't accept: https://standardebooks.org/contribute/accepted-ebooks
