### ISSUE TITLE
epubs do work with kindle including send to kindle.

### ISSUE THREAD

**Issue by kenneth-leblanc** [standardebooks/web#343]
It might be worth updating the "Which File Should I Download?"
compatible epubs do work for send to kindle, (including loading the cover correctly) however, it relies on amazon to do the conversion behind the scenes from epub to some other format.
https://www.techradar.com/news/amazon-kindle-will-finally-support-epub-books-but-theres-a-catch
It might be worth noting this for both the kindle format and the compatible epub format that it is a valid option if you wish to avoid sideloading and wish to just use the send to kindle. Though, perhaps not recommended since the conversion is controlled by amazon.

**Comment by acabal** [comment]
See here: https://standardebooks.org/help/how-to-use-our-ebooks#kindle-faq
