### ISSUE TITLE
More prominent placement of "how-to-use-our-ebooks"

### ISSUE THREAD

**Issue by paulehoffman** [standardebooks/web#35]
In the other repo, I opened an issue on loading the book files and was pointed to the excellent page at https://standardebooks.org/help/how-to-use-our-ebooks. I would not have found that page otherwise. I suggest (without doing a PR because I don't know where y'all would want to put it) that a pointer to how-to-use-our-ebooks be made more prominent on the web site.

**Comment by acabal** [comment]
Right now the page is linked just  below the download links on every ebook page. Right now we don't have a generic "help for readers" section (only a "help for contributors") section, so at some point we should get something like that up and going. I'll put it on the to do list.
