### ISSUE TITLE
Adding OPDS calls for a patron username/password but this is not in the instructions

### ISSUE THREAD

**Issue by evanwolf** [standardebooks/web#355]
The https://standardebooks.org/feeds page has a section called "OPDS 1.2 FEEDS". It shares the link to the feed (https://standardebooks.org/feeds/opds) but doesn't show that you will be prompted for a Patrons Circle email and password. Is the documentation right or the code? 

![screenshot from FB Reader](https://github.com/standardebooks/web/assets/205622/98f365ce-092a-4938-be84-79c1e9495e02)

**Comment by acabal** [comment]
Above that section it says: `Accessing the feeds. Our New Releases feeds are open to everyone. Our other feeds are a benefit of Patrons Circle membership.`

New Releases feeds are available via RSS and Atom at the moment. All OPDS feeds are for Patrons only.
