### ISSUE TITLE
CSP errors in Firefox

### ISSUE THREAD

**Issue by kalafut** [standardebooks/web#372]
Hi. Thanks for the excellent project.

When browsing your main site (https://standardebooks.org) using Firefox, I've found that clicking links results in a blank page. I have to refresh to actually see the page. I see these errors in the console:

<img width="804" alt="image" src="https://github.com/standardebooks/web/assets/211880/e13c71c5-c0f3-4034-8947-a6956768826b">

**Comment by kalafut** [comment]
Actually, this looks to be a compatibility issue with the React Developer Tools extension. When I disable that there are no problems. I'll leave this issue open just in case this is indicative of some other issue.

**Comment by acabal** [comment]
CSP is working fine, I developed this website on Firefox and I've used Firefox every day for almost two decades :) You might consider contacting the React developers about this, though I suspect CSP is probably doing exactly what it's supposed to in this case.
