### ISSUE TITLE
Vocab will be broken on Firefox

### ISSUE THREAD

**Issue by robinwhittleton** [standardebooks/web#38]
Actually, it’s currently broken on Firefox Nightly due to a bug there, but even after the fix for that the combination on no Content-Type and nosniff headers will apparently cause problems:

https://bugzilla.mozilla.org/show_bug.cgi?id=1547076#c7

I guess an easy fix would be to specify Content-Type text/plain?

**Comment by acabal** [comment]
OK, this should be fixed now, that file returns content-type: text/plain
