### ISSUE TITLE
Should reading time also be based on text complexity?

### ISSUE THREAD

**Issue by robinwhittleton** [standardebooks/web#40]
At the moment it’s just number of words with a scaling factor.

**Comment by acabal** [comment]
I don't know if there's a way to calculate that. IIRC right now it's just based on the average adult WPM reading speed.

**Comment by acabal** [comment]
If you can find some kind of accepted way of calculating it, like Flesch-Kincaid calculates reading ease, then we can certainly update the algorithm.

**Comment by robinwhittleton** [comment]
This Readability plugin calculates reading time based on Flesch-Kincaid and the average time of “reading for comprehension”: https://github.com/mikestecker/craft-readability#measuring-how-long-it-should-take-to-read. The Wikipedia answer they took their data from seems to be unsourced though. If we take some sample books of around the same length from SE and run them through [that formula](https://github.com/mikestecker/craft-readability/blob/v1/src/services/ReadabilityService.php#L305-L340) the data changes as so:

- The Railway Children: 3 hours 45 minutes ➡️ 2 hours 3 minutes
- Around the World in 80 Days: 3 hours 51 minutes ➡️ 3 hours 0 minutes
- Beyond Good and Evil: 3 hours 52 minutes ➡️ 5 hours 18 minutes

That feels more realistic than what we currently have, but it’s not exactly scientific, or at least there are no referenced papers to back it up. I’ll carry on looking.

**Comment by robinwhittleton** [comment]
We should probably add “Approximately” in front of the time as well, regardless of whatever solution we go with.

**Comment by acabal** [comment]
Meh, that method is just as fuzzy as ours. If we're going to change this then it should be based on some more widely accepted standard, not what some random plugin decided to do.

**Comment by acabal** [comment]
Closed due to inactivity

**Comment by digitalethics** [comment]
Linking to related [Foliate issue](https://github.com/johnfactotum/foliate/issues/175) to possibly deduplicate efforts.
