### ISSUE TITLE
incorrect link to "Works by Frederick Pohl" spreadsheet

### ISSUE THREAD

**Issue by partev** [standardebooks/web#409]
the link to "Works by Frederick Pohl" https://github.com/standardebooks/web/blob/master/www/contribute/spreadsheets.php#L32

is exactly the same as the link to "Plays by J.M. Synge" and contains plays by Synge.
https://github.com/standardebooks/web/blob/master/www/contribute/spreadsheets.php#L29

**Comment by acabal** [comment]
Thanks, this should be fixed now!
