### ISSUE TITLE
Epub and Kobo

### ISSUE THREAD

**Issue by alvinsight** [standardebooks/web#43]
Hello,
Thank you for your great work, I love the initiative.
In [here](https://github.com/standardebooks/web/blob/master/www/ebooks/ebook.php#L109) you're saying that Epub files are compatible with`All devices and apps except Amazon Kindle and Kobo`.
I'm curious where this comes from, I've personally been using `.epub` files straight from Gutenberg or other publisher's sites with various Kobo devices for a long time and never encountered a problem, the Kobo official store will also let you download files as Epub.
Are most files from publishers actually `kepub` files with a `.epub` extension ?
Thanks

**Comment by acabal** [comment]
Kobo devices will read .epub files, however they will default to the very poor Adobe renderer, and various features like highlighting and notes are disabled. .kepub files use the advanced renderer and allow for additional features you might expect. This is, of course, a Kobo software issue, so you should contact them to complain if you'd like them to get their epub act together! :)
