### ISSUE TITLE
Artwork displays as having been reviewed by its submitter

### ISSUE THREAD

**Issue by acabal** [standardebooks/web#433]
In https://standardebooks.org/artworks/james-northcote/william-godwin, the listing shows that Weijia both submitted and reviewed this submission, which should not be possible. However in the database, the status for this artwork is actually `unverified`, so I think it's just the informational display that's wrong. (Weijia does not have the `CanReviewOwnArtwork` benefit.)

**Comment by acabal** [comment]
Weijia says he submitted the artwork, then later updated it to add the ebook URL. So the error is somewhere in that process.

**Comment by colagrosso** [comment]
Thanks for the report. I'll take a look.

**Comment by colagrosso** [comment]
I was able to reproduce the problem and confirm that #434 fixes it.

For that particular artwork, even though the status is `unverified`, it has a non-null `ReviewerUserId` set. As an admin, once you approve it, your `ReviewerUserId` will overwrite it, and you'll be all set.
