### ISSUE TITLE
Add series / collections to the site

### ISSUE THREAD

**Issue by robinwhittleton** [standardebooks/web#6]
There are several series / collections available on the site, e.g. the Sherlock Holmes and Arsène Lupin stories. Would be good to make these available under individual URLs.

Proposal:

1. Add an /author/AUTHOR_NAME URL endpoint to allow author collections and link to this from ebooks written by that author.
2. Add specific collection metadata that allows a /collection/COLLECTION_NAME pages and link to that from books within that collection (and maybe from the author page?).

Part 1 should be fairly easily accomplished, so in the best agile tradition I’ll start with that.

**Comment by acabal** [comment]
We already have author collections, they're just under /ebooks/AUTHOR-NAME/

**Comment by acabal** [comment]
For collections, just to brainstorm before we start, is there maybe a better word for that to use? PG uses "bookshelves" which I don't particularly like, I think it's stretching the metaphor.

**Comment by robinwhittleton** [comment]
Oh! OK, then I’ll expose these from the ebook pages then. Maybe there’s call for another “More free ebooks” style section with other works by the author (if there is more than one work)?

I think collections works well, along with series. Not sure about bookshelves. I guess the more generic word would be groups?

**Comment by acabal** [comment]
For testing purposes you can just comment out all the APCu stuff in the code. It's basically just a memcache equivalent, for caching purposes only and no other functionality.

**Comment by acabal** [comment]
Implemented in a previous commit.
