### ISSUE TITLE
Add titles to OPDS acquisition links

### ISSUE THREAD

**Issue by johnfactotum** [standardebooks/web#60]
Currently, each entry has four acquisition links, but since the link to EPUB and the link to EPUB 3 have the same type, it's hard for the client or user to tell which is which.

Would it be possible to add an `ttile` attribute to the links containing short labels, like "EPUB", "EPUB 3", "Kobo", "Kindle"? I don't think the spec mentions this, but I've seen some OPDS feeds do this.

If there's a `title`, clients that support `title`s can provide a more useful way for the user to select a link, instead of showing two links with identical types.

**Comment by acabal** [comment]
Good idea, I've added titles in 6a176a8. Thanks!
