### ISSUE TITLE
Provide link to full cover from book page

### ISSUE THREAD

**Issue by bentley** [standardebooks/web#61]
Often I see a nice cover in the search results and would like to look at it more closely in the browser, as opposed to my monochrome e-ink reader. But although the full cover is accessible from the web and linked from the OPDS feed (e.g., [*The Red House Mystery*](https://standardebooks.org/ebooks/a-a-milne/the-red-house-mystery/src/epub/images/cover.svg)), it’s not exposed on the website proper. In fact, although I can right‐click → “View Image” in the search results to view a small thumbnail, on the book’s page itself there is no link to the full cover except the Kindle thumbnail, which won’t display in the browser anyway.

Sorry I’m not confident enough in my CSS ability to come up with a pull request. I tried wrapping the existing cover crop (the `<img>` labeled “The cover for the Standard Ebooks edition of such‐and‐such”) in a `<a>` but it seemed to mess up the design in a way I couldn’t comprehend.

**Comment by acabal** [comment]
I don't think I want to add that just now. The covers on the browse page are enough for most people, and the very curious can go to the Github source and look at the cover there. I don't want to add a bunch of links to the ebook page that most people aren't really going to use.
