### ISSUE TITLE
Fix missing downloads

### ISSUE THREAD

**Issue by digitalethics** [standardebooks/web#66]
https://standardebooks.org/ebooks/j-w-von-goethe/the-sorrows-of-young-werther/r-d-boylan/dist/j-w-von-goethe_the-sorrows-of-young-werther_r-d-boylan.epub

![missingdownload](https://user-images.githubusercontent.com/57445091/85153424-7baba700-b256-11ea-8efa-d86abeead097.png)

**Comment by acabal** [comment]
This should be fixed now, thanks!

**Comment by digitalethics** [comment]
Fixed, thanks a lot!
