### ISSUE TITLE
Fix missing downloads

### ISSUE THREAD

**Issue by digitalethics** [standardebooks/web#67]
I have spotted a few more: 

https://standardebooks.org/ebooks/maurice-leblanc/the-hollow-needle/alexander-teixeira-de-mattos/dist/maurice-leblanc_the-hollow-needle_alexander-teixeira-de-mattos.epub

https://standardebooks.org/ebooks/luigi-pirandello/six-characters-in-search-of-an-author/edward-storer/dist/luigi-pirandello_six-characters-in-search-of-an-author_edward-storer.epub

https://standardebooks.org/ebooks/yevgeny-zamyatin/we/gregory-zilboorg/dist/yevgeny-zamyatin_we_gregory-zilboorg.epub

https://standardebooks.org/ebooks/ludwig-wittgenstein/tractatus-logico-philosophicus/c-k-ogden/dist/ludwig-wittgenstein_tractatus-logico-philosophicus_c-k-ogden.epub

https://standardebooks.org/ebooks/maurice-leblanc/the-extraordinary-adventures-of-arsene-lupin-gentleman-burglar/george-morehead/dist/maurice-leblanc_the-extraordinary-adventures-of-arsene-lupin-gentleman-burglar_george-morehead.epub

https://standardebooks.org/ebooks/maurice-leblanc/the-eight-strokes-of-the-clock/alexander-teixeira-de-mattos/dist/maurice-leblanc_the-eight-strokes-of-the-clock_alexander-teixeira-de-mattos.epub

https://standardebooks.org/ebooks/maurice-leblanc/the-crystal-stopper/alexander-teixeira-de-mattos/dist/maurice-leblanc_the-crystal-stopper_alexander-teixeira-de-mattos.epub

https://standardebooks.org/ebooks/maurice-leblanc/the-confessions-of-arsene-lupin/alexander-teixeira-de-mattos/dist/maurice-leblanc_the-confessions-of-arsene-lupin_alexander-teixeira-de-mattos.epub

https://standardebooks.org/ebooks/maurice-leblanc/arsene-lupin-versus-herlock-sholmes/george-morehead/dist/maurice-leblanc_arsene-lupin-versus-herlock-sholmes_george-morehead.epub

https://standardebooks.org/ebooks/maurice-leblanc/the-golden-triangle/alexander-teixeira-de-mattos/dist/maurice-leblanc_the-golden-triangle_alexander-teixeira-de-mattos.epub

https://standardebooks.org/ebooks/maurice-leblanc/the-secret-of-sarek/alexander-teixeira-de-mattos/dist/maurice-leblanc_the-secret-of-sarek_alexander-teixeira-de-mattos.epub

https://standardebooks.org/ebooks/maurice-leblanc/the-teeth-of-the-tiger/alexander-teixeira-de-mattos/dist/maurice-leblanc_the-teeth-of-the-tiger_alexander-teixeira-de-mattos.epub

https://standardebooks.org/ebooks/selma-lagerlof/the-story-of-gosta-berling/pauline-bancroft-flach/dist/selma-lagerlof_the-story-of-gosta-berling_pauline-bancroft-flach.epub

https://standardebooks.org/ebooks/maurice-leblanc/813/alexander-teixeira-de-mattos/dist/maurice-leblanc_813_alexander-teixeira-de-mattos.epub

https://standardebooks.org/ebooks/nikolai-gogol/dead-souls/d-j-hogarth/dist/nikolai-gogol_dead-souls_d-j-hogarth.epub

https://standardebooks.org/ebooks/vsevolod-garshin/short-fiction/rowland-smith/dist/vsevolod-garshin_short-fiction_rowland-smith.epub

https://standardebooks.org/ebooks/selma-lagerlof/the-wonderful-adventures-of-nils/velma-swanston-howard/dist/selma-lagerlof_the-wonderful-adventures-of-nils_velma-swanston-howard.epub

https://standardebooks.org/ebooks/victor-hugo/notre-dame-de-paris/isabel-f-hapgood/dist/victor-hugo_notre-dame-de-paris_isabel-f-hapgood.epub

https://standardebooks.org/ebooks/victor-hugo/les-miserables/isabel-f-hapgood/dist/victor-hugo_les-miserables_isabel-f-hapgood.epub

https://standardebooks.org/ebooks/suetonius/the-lives-of-the-caesars/j-c-rolfe/dist/suetonius_the-lives-of-the-caesars_j-c-rolfe.epub

https://standardebooks.org/ebooks/seneca/dialogues/aubrey-stewart/dist/seneca_dialogues_aubrey-stewart.epub

https://standardebooks.org/ebooks/roswitha-of-gandersheim/plays/christopher-st-john/dist/roswitha-of-gandersheim_plays_christopher-st-john.epub

https://standardebooks.org/ebooks/omar-khayyam/the-rubaiyat-of-omar-khayyam/edward-fitzgerald/dist/omar-khayyam_the-rubaiyat-of-omar-khayyam_edward-fitzgerald.epub

https://standardebooks.org/ebooks/nikolai-gogol/short-fiction/claud-field_isabel-f-hapgood_vizetelly-and-company_george-tolstoy/dist/nikolai-gogol_short-fiction_claud-field_isabel-f-hapgood_vizetelly-and-company_george-tolstoy.epub

https://standardebooks.org/ebooks/niccolo-machiavelli/the-prince/w-k-marriott/dist/niccolo-machiavelli_the-prince_w-k-marriott.epub

https://standardebooks.org/ebooks/miguel-de-cervantes-saavedra/don-quixote/john-ormsby/dist/miguel-de-cervantes-saavedra_don-quixote_john-ormsby.epub

https://standardebooks.org/ebooks/maurice-leblanc/the-secret-tomb/alexander-teixeira-de-mattos/dist/maurice-leblanc_the-secret-tomb_alexander-teixeira-de-mattos.epub

https://standardebooks.org/ebooks/marcus-aurelius/meditations/george-long/dist/marcus-aurelius_meditations_george-long.epub

https://standardebooks.org/ebooks/lord-dunsany/the-book-of-wonder/sidney-h-sime/dist/lord-dunsany_the-book-of-wonder_sidney-h-sime.epub

https://standardebooks.org/ebooks/lewis-carroll/through-the-looking-glass/john-tenniel/dist/lewis-carroll_through-the-looking-glass_john-tenniel.epub

**Comment by acabal** [comment]
These should be fixed now, thanks!

**Comment by digitalethics** [comment]
Fantastic! Thanks a lot!
