### ISSUE TITLE
Support searching the OPDS feed

### ISSUE THREAD

**Issue by digitalethics** [standardebooks/web#68]
It would be great to have the option to search the Standard Ebooks OPDS feed. Foliate has the capability to perform searches. Would you consider implementing this so that we can increase ebook discovery in both projects? For now, the option to search the SE feed has been [deactivated](https://github.com/johnfactotum/foliate/issues/478) in Foliate until implemented on your side.

**Comment by acabal** [comment]
I don't know about implementing searching in OPDS. What would we need to do?

**Comment by digitalethics** [comment]
> I don't know about implementing searching in OPDS. What would we need to do?

You can find more information on implementing search in the [OPDS Specs](https://specs.opds.io/opds-1.2#3-search).

**Comment by acabal** [comment]
OK, this should be implemented now.
