### ISSUE TITLE
Add schema.org markup?

### ISSUE THREAD

**Issue by robinwhittleton** [standardebooks/web#82]
I’d be happy to do this, but a quick check to see if it’s wanted first.

schema.org defines book microdata: https://schema.org/Book . This is used by search engines to help categorise and display data. We can add this (probably most easily as JSON-LD) to each book page to help people find us.

**Comment by acabal** [comment]
I think we already have this on each ebook's page?

**Comment by robinwhittleton** [comment]
Right, I’m actually an idiot. I was looking for schema attributes attached to the book markup and missing the massive JSON-LD block at the top of the page 🤦‍♂️
