### ISSUE TITLE
"Don’t use Calibre to transfer the .kepub.epub file!"

### ISSUE THREAD

**Issue by SiIky** [standardebooks/web#83]
Hello! Awesome project, thanks for your hard work in creating quality ebooks!

![image](https://user-images.githubusercontent.com/12852780/94362733-5cbe7b80-00b5-11eb-92d7-1bc7ff834a08.png)

I've found this bit of advice on the website, but it's not entirely true. I use Calibre to transfer KEPUBs to my Kobo, and my Kobo correctly identifies them as KEPUB. I don't know why/where this came from, but I can imagine someone adding `.kepub.epub` files to Calibre without success, because Calibre doesn't recognise these as KEPUB -- it does, however, recognise `.kepub`. And so, whenever I download a KEPUB from Standard Ebooks, I just remove the `.epub` extension, add it to Calibre, and send it to my Kobo.

https://github.com/standardebooks/web/blob/eed33559169ec4331c88ba16dd67fbfa2db8ab4d/www/help/how-to-use-our-ebooks.php#L67

**Comment by acabal** [comment]
Perhaps, but many Kobo users have the Kobo Calibre driver installed, which will conflict with our specially-prepared kepubs in subtle ways. It's easier simply to tell people to drag and drop in a file manager and not use Calibre, than to say it's OK but with many complex exceptions. At the end of the day, it is us who will get blamed, even though it may have been the user's fault for not using Calibre correctly.

**Comment by SiIky** [comment]
> Perhaps, but many Kobo users have the Kobo Calibre driver installed, which will conflict with our specially-prepared kepubs in subtle ways.

What do you mean here? That the driver alters the file in some way(s), instead of simply copying it?

> It's easier simply to tell people to drag and drop in a file manager and not use Calibre, than to say it's OK but with many complex exceptions.

There's no exception, really: just add the `.kepub` file to Calibre -- ignoring the Kobo driver issue(s). But I understand the following reason.

> At the end of the day, it is us who will get blamed, even though it may have been the user's fault for not using Calibre correctly.

I can see that happening, unfortunately...

**Comment by acabal** [comment]
> What do you mean here? That the driver alters the file in some way(s), instead of simply copying it?

That's right, Calibre alters epub files sent to Kobo devices when using the Kobo driver. Since ours are specially prepared, Calibre's alterations will result in subtle errors.

**Comment by SiIky** [comment]
> Calibre alters epub files sent to Kobo devices when using the Kobo driver.

Just epub files, or kepub files too? It's not to pester you, I just don't want any misunderstandings.

**Comment by acabal** [comment]
Last I checked, both
