### ISSUE TITLE
thumbnail instructions for windows slightly incorrect

### ISSUE THREAD

**Issue by crose4** [standardebooks/web#84]
https://standardebooks.org/help/how-to-use-our-ebooks#transferring-to-your-ereader

this page describes copying over the thumbnail files to the system folder on the kindle. slight inaccuracy here for at least windows 10. The system folder isn't a hidden folder (at least on the 10th generation kindle) but a "protected operating system file." To properly see it, you must uncheck "Hide protected operating system files" from the file explorer advanced options.

**Comment by acabal** [comment]
Thanks, I've updated the text on the web site to reflect that.
