### ISSUE TITLE
Back button on mobile is too wide

### ISSUE THREAD

**Issue by priner** [standardebooks/web#86]
In the ebooks grid (on the first page), the grayed out version of the back button contains the word "back" (the way it does on desktop) which makes it really wide and that makes the whole site slightly wider than my screen width. It also looks inconsistent with the non-grayed out version.
![photo_2020-11-01_15-05-38](https://user-images.githubusercontent.com/51519088/97805036-e7b20900-1c53-11eb-89f9-85197dd5cd0f.jpg)
![photo_2020-11-01_15-05-33](https://user-images.githubusercontent.com/51519088/97805025-d10bb200-1c53-11eb-89c5-b0cc7db2fb86.jpg)

**Comment by acabal** [comment]
Thanks, this should be fixed now!
