### ISSUE TITLE
Typo on page about acceptable eBooks

### ISSUE THREAD

**Issue by platypusguy** [standardebooks/web#87]
On this page:
[https://github.com/standardebooks/web/blob/master/www/contribute/accepted-ebooks.php](https://github.com/standardebooks/web/blob/master/www/contribute/accepted-ebooks.php)

you write: "This includes obscure histories that are not otherwise notable and have been superceded by modern research..."

Superceded is a misspelled. It should be: superseded.

**Comment by acabal** [comment]
Thanks, this should be fixed now!
