### ISSUE TITLE
Add the Publication date of books

### ISSUE THREAD

**Issue by pauloxnet** [standardebooks/web#92]
The publication date of a book it's a very useful information to select a book to read.

Would be very helpful to show it in the books section and permit to order by it.

**Comment by acabal** [comment]
The publication date on books is often not obvious. Many older books were first published serially in magazines before being published as novels; which date would we list? Which date of which edition? What about short fiction compilations where works span a date range, and other compilations? So, that's not something we're going to be doing right now. Wikipedia is a good starting point to decide when a book was published if a person is interested.

**Comment by pauloxnet** [comment]
Thanks for the explanation.

**Comment by acabal** [comment]
> Perhaps this issue should be reopened because something is better than nothing

I disagree, we're not going to be doing this request. Sorry!
