### ISSUE TITLE
interactive-sr for everyone seems to have broken on Mac recently

### ISSUE THREAD

**Issue by robinwhittleton** [standardebooks/web#96]
https://github.com/standardebooks/web/commit/a6971750be1aa97abeab758f3c5a48bf0b16d291 updated the regex for the “everyone” interactive-sr from `/\v([Ee])very one(\s+of)@\!/\1veryone/` to `/\v([Ee]ach and )@*<\!([Ee])very one(\s+of)@\!/\1veryone/`. This seems to have broken the command on the default Mac install of vim with the following error (2nd line repeated for each file):

```
Error detected while processing command line:
E59: invalid character after @
```

The default report for `vim --version` (on macOS 11 Big Sur) is:

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Nov 23 2020 06:06:21)
macOS version
Included patches: 1-850
Compiled by root@apple.com
```

plus a big listing of compiled features.

I’m a vim newbie and have no idea how to start debugging this. Is it something you’ve seen before?

**Comment by acabal** [comment]
Looks like a stray `*` got in there somehow when I was editing the file. This should be fixed now!
